theme = "soho"
baseurl = "http://www.corynissen.com/"
languageCode = "en"
title = "Cory Nissen"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "Cory Nissen"
description = "Blog"
gravatar = "corynissen@gmail.com"
images = ["images/profile.jpg"]
profilePicture = "images/profile.jpg"
copyright = "Cory Nissen"
license = "CC0"
licenseURL = "https://creativecommons.org/choose/zero/"
builtWith = false
mainSections = ["posts"]

## Set custom theme color.
 themeColor = "#257ce3"

  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/cory-nissen/"

  [[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/corynissen"

  [[params.socialIcons]]
  icon = "fab fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/corynissen"
  
  [[params.socialIcons]]
  icon = "fa fa-map-marker"
  title = "Baseballmapper"
  url = "http://www.baseballmapper.com"
  
  [[params.socialIcons]]
  icon = "fab fa-flickr"
  title = "Flickr"
  url = "https://www.flickr.com/photos/189563624@N02/page2"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
